FROM node:18-alpine3.19

WORKDIR /app

# Install dependencies first (cached layer)
COPY package*.json ./
RUN npm install

# Update system packages to address vulnerabilities
RUN apk update && apk upgrade --no-cache

# Copy source
COPY . .
RUN npm run build
# Default command (with hot-reload)
CMD ["npm", "run", "start"]